export default [
  {
    index: 0,
    name: '川菜',
    city: [
      { name: '四川', value: '川菜', selected: false },
      { name: '重庆', value: '川菜', selected: false }
    ],
    list: [
      { name: '四川火锅', isSelect: false },
      { name: '鱼香肉丝', isSelect: false },
      { name: '辣子鸡', isSelect: false },
      { name: '夫妻肺片', isSelect: false },
      { name: '水煮肉片', isSelect: false },
      { name: '水煮鱼', isSelect: false },
      { name: '麻婆豆腐', isSelect: false },
      { name: '毛血旺', isSelect: false },
      { name: '口水鸡', isSelect: false },
      { name: '灯影牛肉', isSelect: false },
      { name: '棒棒鸡', isSelect: false },
      { name: '香辣虾', isSelect: false },
      { name: '麻辣香水鱼', isSelect: false },
      { name: '板栗烧鸡', isSelect: false },
      { name: '蚂蚁上树', isSelect: false },
      { name: '甜皮鸭', isSelect: false },
      { name: '冷吃兔', isSelect: false },
      { name: '钵钵鸡', isSelect: false },
      { name: '冷锅串串', isSelect: false },
      { name: '锅巴肉片', isSelect: false }
    ],
    selectNum: 0
  },
  {
    index: 1,
    name: '鲁菜',
    city: [{ name: '山东', value: '鲁菜', selected: false }],
    list: [
      { name: '一品豆腐', isSelect: false },
      { name: '九转大肠', isSelect: false },
      { name: '油爆双脆', isSelect: false },
      { name: '四喜丸子', isSelect: false },
      { name: '醋椒鱼', isSelect: false },
      { name: '芫爆鱿鱼卷', isSelect: false },
      { name: '胶东四大拌', isSelect: false },
      { name: '招远蒸丸', isSelect: false },
      { name: '葱椒鱼', isSelect: false },
      { name: '糖酱鸡块', isSelect: false },
      { name: '油泼豆莛', isSelect: false },
      { name: '砂锅散丹', isSelect: false },
      { name: '全爆', isSelect: false },
      { name: '布袋鸡', isSelect: false }
    ],
    selectNum: 0
  },
  {
    index: 2,
    name: '粤菜',
    city: [
      { name: '广东', value: '粤菜', selected: false },
      { name: '澳门', value: '粤菜', selected: false }
    ],
    list: [
      { name: '白切鸡', isSelect: false },
      { name: '蜜汁叉烧', isSelect: false },
      { name: '脆皮烧肉', isSelect: false },
      { name: '盐焗鸡', isSelect: false },
      { name: '猪肚鸡', isSelect: false },
      { name: '潮汕卤鹅', isSelect: false },
      { name: '广式烧填鸭', isSelect: false },
      { name: '老火靓汤', isSelect: false },
      { name: '罗汉斋', isSelect: false },
      { name: '蚝仔烙', isSelect: false },
      { name: '菠萝咕噜肉', isSelect: false },
      { name: '玫瑰豉油鸡', isSelect: false },
      { name: '芙蓉虾', isSelect: false },
      { name: '沙茶牛肉', isSelect: false },
      { name: '客家酿豆腐', isSelect: false },
      { name: '潮州牛肉丸', isSelect: false },
      { name: '肠粉', isSelect: false },
      { name: '姜汁撞奶', isSelect: false },
      { name: '煲仔饭', isSelect: false }
    ],
    selectNum: 0
  },
  {
    index: 3,
    name: '苏菜',
    city: [{ name: '江苏', value: '苏菜', selected: false }],
    list: [
      { name: '叫化鸡', isSelect: false },
      { name: '金陵丸子', isSelect: false },
      { name: '烤方', isSelect: false },
      { name: '水晶肴肉', isSelect: false },
      { name: '清炖鸡孚', isSelect: false },
      { name: '盐水鸭', isSelect: false },
      { name: '清汤火方', isSelect: false },
      { name: '水晶肴蹄', isSelect: false },
      { name: '松鼠桂鱼', isSelect: false },
      { name: '奶汤鱼皮', isSelect: false },
      { name: '鸡汁煮干丝', isSelect: false },
      { name: '丁香排骨', isSelect: false },
      { name: '叉烤鸭', isSelect: false },
      { name: '雪花蟹斗', isSelect: false },
      { name: '红烧划水', isSelect: false },
      { name: '无锡肉骨头', isSelect: false },
      { name: '天目湖砂锅鱼头', isSelect: false },
      { name: '淮安软兜', isSelect: false },
      { name: '桂花糯米藕', isSelect: false }
    ],
    selectNum: 0
  },
  {
    index: 4,
    name: '浙菜',
    city: [{ name: '浙江', value: '浙菜', selected: false }],
    list: [
      { name: '西湖醋鱼', isSelect: false },
      { name: '东坡肉', isSelect: false },
      { name: '干炸响铃', isSelect: false },
      { name: '油焖春笋', isSelect: false },
      { name: '龙井虾仁', isSelect: false },
      { name: '杭州煨鸡', isSelect: false },
      { name: '拔丝蜜桔', isSelect: false },
      { name: '西湖莼菜汤', isSelect: false },
      { name: '蛤蜊黄鱼羹', isSelect: false },
      { name: '叫化童鸡', isSelect: false },
      { name: '三丝拌蛏', isSelect: false },
      { name: '丝瓜卤蒸黄鱼', isSelect: false },
      { name: '雪菜大汤黄鱼', isSelect: false },
      { name: '冰糖甲鱼', isSelect: false },
      { name: '嘉兴粽子', isSelect: false },
      { name: '宁波汤团', isSelect: false },
      { name: '湖州千张包子', isSelect: false }
    ],
    selectNum: 0
  },
  {
    index: 5,
    name: '湘菜',
    city: [{ name: '湖南', value: '湘菜', selected: false }],
    list: [
      { name: '剁椒鱼头', isSelect: false },
      { name: '永州血鸭', isSelect: false },
      { name: '吉首酸肉', isSelect: false },
      { name: '组庵豆腐', isSelect: false },
      { name: '腊味合蒸', isSelect: false },
      { name: '姊妹团子', isSelect: false },
      { name: '栖凤渡鱼粉', isSelect: false },
      { name: '湘西外婆菜', isSelect: false },
      { name: '干锅肥肠', isSelect: false },
      { name: '地锅鸡', isSelect: false },
      { name: '秘制口味蛇', isSelect: false },
      { name: '岳阳姜辣蛇', isSelect: false },
      { name: '宁远酿豆腐', isSelect: false },
      { name: '干蒸鸡', isSelect: false },
      { name: '香辣羊肚丝', isSelect: false },
      { name: '擂钵茄子', isSelect: false },
      { name: '长沙臭豆腐', isSelect: false }
    ],
    selectNum: 0
  },
  {
    index: 6,
    name: '闽菜',
    city: [{ name: '福建', value: '闽菜', selected: false }],
    list: [
      { name: '佛跳墙', isSelect: false },
      { name: '福州鱼丸', isSelect: false },
      { name: '鼎边糊', isSelect: false },
      { name: '漳州卤面', isSelect: false },
      { name: '厦门沙茶面', isSelect: false },
      { name: '西施舌芙蓉蛋', isSelect: false },
      { name: '面线糊', isSelect: false },
      { name: '闽南咸饭', isSelect: false },
      { name: '荔枝肉', isSelect: false },
      { name: '白雪鸡', isSelect: false },
      { name: '红糟鱼排', isSelect: false },
      { name: '乌柳居', isSelect: false },
      { name: '长汀豆腐干', isSelect: false },
      { name: '闽南豆皮卷', isSelect: false },
      { name: '酸菜牛肉', isSelect: false },
      { name: '海鲜鱼面', isSelect: false },
      { name: '醉排骨', isSelect: false }
    ],
    selectNum: 0
  },
  {
    index: 7,
    name: '徽菜',
    city: [{ name: '安徽', value: '徽菜', selected: false }],
    list: [
      { name: '红烧臭鳜鱼', isSelect: false },
      { name: '徽州毛豆腐', isSelect: false },
      { name: '清蒸石鸡', isSelect: false },
      { name: '问政山笋', isSelect: false },
      { name: '黄山炖鸽', isSelect: false },
      { name: '杨梅丸子', isSelect: false },
      { name: '一品锅', isSelect: false },
      { name: '刀板香', isSelect: false },
      { name: '虎皮毛豆腐', isSelect: false },
      { name: '凤炖牡丹', isSelect: false }
    ],
    selectNum: 0
  },
  {
    index: 8,
    name: '京菜',
    city: [{ name: '北京', value: '京菜', selected: false }],
    list: [
      { name: '北京烤鸭', isSelect: false },
      { name: '涮羊肉', isSelect: false },
      { name: '京酱肉丝', isSelect: false },
      { name: '芥末鸡丝', isSelect: false },
      { name: '松鼠黄鱼', isSelect: false },
      { name: '炒麻豆腐', isSelect: false },
      { name: '炸香椿鱼儿', isSelect: false },
      { name: '素烧柚子瓤', isSelect: false },
      { name: '鱼头泡饼', isSelect: false },
      { name: '驴打滚', isSelect: false },
      { name: '豆汁', isSelect: false },
      { name: '炒肝', isSelect: false },
      { name: '姜汁排叉', isSelect: false },
      { name: '炸灌肠', isSelect: false }
    ],
    selectNum: 0
  },
  {
    index: 9,
    name: '东北菜',
    city: [
      { name: '黑龙江', value: '东北菜', selected: false },
      { name: '吉林', value: '东北菜', selected: false },
      { name: '辽宁', value: '东北菜', selected: false }
    ],
    list: [
      { name: '地三鲜', isSelect: false },
      { name: '拔丝地瓜', isSelect: false },
      { name: '锅包肉 ', isSelect: false },
      { name: '溜肉段', isSelect: false },
      { name: '白肉血肠', isSelect: false },
      { name: '熘肥肠', isSelect: false },
      { name: '东北乱炖 ', isSelect: false },
      { name: '酱骨架 ', isSelect: false },
      { name: '爆煎鲤鱼', isSelect: false },
      { name: '猪肉炖粉条', isSelect: false },
      { name: '小鸡炖蘑菇', isSelect: false },
      { name: '花椒嫩醉鸡', isSelect: false },
      { name: '烩酸辣干丝 ', isSelect: false },
      { name: '蛋泡银鱼 ', isSelect: false },
      { name: '芹菜鱼丝', isSelect: false },
      { name: '熘花胗', isSelect: false },
      { name: '茄汁草鱼片', isSelect: false },
      { name: '鸭腰烧口蘑', isSelect: false },
      { name: '软炸鱼', isSelect: false },
      { name: '甩袖汤', isSelect: false }
    ],
    selectNum: 0
  },
  {
    index: 10,
    name: '西北菜',
    city: [
      { name: '陕西', value: '西北菜', selected: false },
      { name: '甘肃', value: '西北菜', selected: false },
      { name: '宁夏', value: '西北菜', selected: false },
      { name: '青海', value: '西北菜', selected: false },
      { name: '新疆', value: '西北菜', selected: false }
    ],
    list: [
      { name: '岐山臊子面', isSelect: false },
      { name: '兰州牛肉面', isSelect: false },
      { name: '陕西凉皮', isSelect: false },
      { name: '油泼面', isSelect: false },
      { name: '莜面鱼鱼', isSelect: false },
      { name: '手抓孜然羊排', isSelect: false },
      { name: '新疆大盘鸡', isSelect: false },
      { name: '手抓羊肉', isSelect: false },
      { name: '羊肉泡馍', isSelect: false },
      { name: '炒麻什', isSelect: false },
      { name: '肉夹馍', isSelect: false },
      { name: '羊肉烩麻食', isSelect: false },
      { name: '葱油洋芋擦擦', isSelect: false },
      { name: '蒙古黄油饼', isSelect: false },
      { name: '菜豆腐', isSelect: false },
      { name: '黄面馍馍', isSelect: false },
      { name: '陕西特产八宝咸油茶', isSelect: false }
    ],
    selectNum: 0
  },
  {
    index: 11,
    name: '湖北菜',
    city: [{ name: '湖北', value: '湖北菜', selected: false }],
    list: [
      { name: '清蒸武昌鱼', isSelect: false },
      { name: '排骨藕汤', isSelect: false },
      { name: '沔阳三蒸', isSelect: false },
      { name: '粉蒸甲鱼', isSelect: false },
      { name: '黄陂三合', isSelect: false },
      { name: '酸辣藕带', isSelect: false },
      { name: '红菜苔炒腊肉', isSelect: false },
      { name: '炮蒸鳝鱼', isSelect: false },
      { name: '皮条鳝鱼', isSelect: false },
      { name: '千张肉', isSelect: false },
      { name: '应山滑肉', isSelect: false },
      { name: '黄焖九宫石鸡', isSelect: false },
      { name: '桔瓣鱼元', isSelect: false },
      { name: '干烧铜鱼', isSelect: false },
      { name: '热干面', isSelect: false },
      { name: '牛油面', isSelect: false },
      { name: '三鲜豆皮', isSelect: false },
      { name: '武汉面窝', isSelect: false },
      { name: '湖北鱼糕', isSelect: false }
    ],
    selectNum: 0
  },
  {
    index: 12,
    name: '上海菜',
    city: [{ name: '上海', value: '上海菜', selected: false }],
    list: [
      { name: '腌笃鲜', isSelect: false },
      { name: '炒鳝糊', isSelect: false },
      { name: '八宝鸭', isSelect: false },
      { name: '沪江排骨', isSelect: false },
      { name: '上海醉蟹', isSelect: false },
      { name: '鹅肝酱片', isSelect: false },
      { name: '南翔小笼包', isSelect: false },
      { name: '腐乳汁烧油菜', isSelect: false },
      { name: '鸡火干丝', isSelect: false },
      { name: '酒香草头', isSelect: false },
      { name: '醉虾', isSelect: false },
      { name: '猪油百果松糕', isSelect: false },
      { name: '咸青鱼烧冬笋', isSelect: false },
      { name: '豆腐衣包肉', isSelect: false },
      { name: '香酥腐皮卷', isSelect: false }
    ],
    selectNum: 0
  },
  {
    index: 13,
    name: '天津菜',
    city: [{ name: '天津', value: '天津菜', selected: false }],
    list: [
      { name: '老爆三', isSelect: false },
      { name: '贴饽饽熬小鱼', isSelect: false },
      { name: '罗汉肚', isSelect: false },
      { name: '罾蹦鲤鱼', isSelect: false },
      { name: '天津大麻花', isSelect: false },
      { name: '锅塌里脊', isSelect: false },
      { name: '独面筋', isSelect: false },
      { name: '炒青虾仁', isSelect: false },
      { name: '八珍豆腐', isSelect: false },
      { name: '官烧目鱼', isSelect: false },
      { name: '独流焖鱼', isSelect: false }
    ],
    selectNum: 0
  },
  {
    index: 14,
    name: '云南菜',
    city: [{ name: '云南', value: '云南菜', selected: false }],
    list: [
      { name: '沾益辣子鸡', isSelect: false },
      { name: '汽锅鸡', isSelect: false },
      { name: '金钱云腿', isSelect: false },
      { name: '菠萝饭 ', isSelect: false },
      { name: '芫爆松茸', isSelect: false },
      { name: '辣炒野生菌 ', isSelect: false },
      { name: '红烧鸡棕菌', isSelect: false },
      { name: '香茅草烤鱼', isSelect: false },
      { name: '傣味菠萝饭', isSelect: false },
      { name: '夹沙乳扇 ', isSelect: false },
      { name: '酸浆米线', isSelect: false },
      { name: '云南春卷', isSelect: false },
      { name: '曲靖蒸饵丝', isSelect: false },
      { name: '椰香泡椒煎牛柳', isSelect: false }
    ],
    selectNum: 0
  },
  {
    index: 15,
    name: '贵州菜',
    city: [{ name: '贵州', value: '贵州菜', selected: false }],
    list: [
      { name: '稻草排骨', isSelect: false },
      { name: '丝娃娃', isSelect: false },
      { name: '酸汤鱼', isSelect: false },
      { name: '旧州辣子鸡', isSelect: false },
      { name: '鱼包韭菜', isSelect: false },
      { name: '竹筒饭', isSelect: false },
      { name: '滇味凉拌折耳根', isSelect: false },
      { name: '黔味凉拌茄子', isSelect: false },
      { name: '鱼腥草炒腊肉', isSelect: false },
      { name: '滇味凉拌薄荷', isSelect: false }
    ],
    selectNum: 0
  },
  {
    index: 16,
    name: '广西菜',
    city: [{ name: '广西', value: '广西菜', selected: false }],
    list: [
      { name: '马肉米粉', isSelect: false },
      { name: '纸包鸡', isSelect: false },
      { name: '桂林米粉', isSelect: false },
      { name: '马蹄肉饼', isSelect: false },
      { name: '打油茶', isSelect: false },
      { name: '柳州酿豆腐泡', isSelect: false },
      { name: '巴马香猪', isSelect: false },
      { name: '柠檬鸭', isSelect: false },
      { name: '酸杨桃炒牛肉', isSelect: false },
      { name: '清蒸漓江桂鱼', isSelect: false }
    ],
    selectNum: 0
  },
  {
    index: 17,
    name: '山西菜',
    city: [{ name: '山西', value: '山西菜', selected: false }],
    list: [
      { name: '过油肉', isSelect: false },
      { name: '喇嘛肉', isSelect: false },
      { name: '太原头脑', isSelect: false },
      { name: '刀削面', isSelect: false },
      { name: '拨鱼', isSelect: false },
      { name: '猫耳朵', isSelect: false },
      { name: '闻喜饼', isSelect: false },
      { name: '猪血灌肠', isSelect: false },
      { name: '定襄蒸肉', isSelect: false },
      { name: '鹌鹑茄子', isSelect: false },
      { name: '沙棘开口笑', isSelect: false },
      { name: '西红柿烩鱼鱼', isSelect: false }
    ],
    selectNum: 0
  },
  {
    index: 18,
    name: '河南菜',
    city: [{ name: '河南', value: '河南菜', selected: false }],
    list: [
      { name: '汴京烤鸭', isSelect: false },
      { name: '炸八块', isSelect: false },
      { name: '葱扒羊肉', isSelect: false },
      { name: '开封灌汤包', isSelect: false },
      { name: '糖醋软熘鱼焙面', isSelect: false },
      { name: '胡辣汤', isSelect: false },
      { name: '烩面', isSelect: false },
      { name: '炸紫酥肉', isSelect: false },
      { name: '双麻火烧', isSelect: false },
      { name: '鸡蛋灌饼', isSelect: false },
      { name: '油旋', isSelect: false },
      { name: '煎扒青鱼头尾', isSelect: false }
    ],
    selectNum: 0
  },
  {
    index: 19,
    name: '江西菜',
    city: [{ name: '江西', value: '江西菜', selected: false }],
    list: [
      { name: '三杯鸡', isSelect: false },
      { name: '五元龙凤汤', isSelect: false },
      { name: '豫章酥鸡', isSelect: false },
      { name: '瓦罐汤', isSelect: false },
      { name: '冬笋干烧肉', isSelect: false },
      { name: '藜蒿炒腊肉', isSelect: false },
      { name: '上饶汤粉', isSelect: false },
      { name: '原笼船板肉', isSelect: false },
      { name: '浔阳鱼片', isSelect: false },
      { name: '兴国豆腐', isSelect: false },
      { name: '米粉牛肉', isSelect: false },
      { name: '黄元米果', isSelect: false },
      { name: '豆泡烧肉', isSelect: false },
      { name: '井冈山烟笋', isSelect: false },
      { name: '鄱阳湖狮子头', isSelect: false },
      { name: '南安板鸭', isSelect: false },
      { name: '贵溪捺菜', isSelect: false }
    ],
    selectNum: 0
  },
  {
    index: 20,
    name: '河北菜',
    city: [{ name: '河北', value: '河北菜', selected: false }],
    list: [
      { name: '驴肉火烧', isSelect: false },
      { name: '总督豆腐', isSelect: false },
      { name: '阳春白雪', isSelect: false },
      { name: '水晶鸡片', isSelect: false },
      { name: '桂花鱼翅', isSelect: false },
      { name: '烹虾段', isSelect: false },
      { name: '李家狮子头', isSelect: false },
      { name: '李鸿章烩菜', isSelect: false },
      { name: '鸡里蹦', isSelect: false },
      { name: '荷包里脊', isSelect: false },
      { name: '锅包肘子', isSelect: false },
      { name: '炒代蟹', isSelect: false }
    ],
    selectNum: 0
  },
  {
    index: 21,
    name: '港台菜',
    city: [
      { name: '香港', value: '港台菜', selected: false },
      { name: '台湾', value: '港台菜', selected: false }
    ],
    list: [
      { name: '胡椒饼', isSelect: false },
      { name: '甜不辣', isSelect: false },
      { name: '万峦猪脚', isSelect: false },
      { name: '担仔面', isSelect: false },
      { name: '润饼', isSelect: false },
      { name: '烧仙草', isSelect: false },
      { name: '蒜茸蒸白菜', isSelect: false },
      { name: '虱目鱼肚粥', isSelect: false },
      { name: '筒仔米糕', isSelect: false },
      { name: '花枝羹', isSelect: false },
      { name: '鱼酥羹', isSelect: false },
      { name: '栗子莲藕汤', isSelect: false },
      { name: '橄榄肉碎四季豆', isSelect: false },
      { name: '大肠蚵仔面线', isSelect: false },
      { name: '大饼包小饼', isSelect: false },
      { name: '猪血糕', isSelect: false },
      { name: '东山鸭头', isSelect: false },
    ],
    selectNum: 0
  },
  {
    index: 22,
    name: '蒙古菜',
    city: [{ name: '内蒙古', value: '蒙古菜', selected: false }],
    list: [
      { name: '烤羊腿', isSelect: false },
      { name: '马奶酒', isSelect: false },
      { name: '莜麦面', isSelect: false },
      { name: '哈达饼', isSelect: false },
      { name: '蒙古馅饼', isSelect: false },
      { name: '蜜麻叶', isSelect: false },
      { name: '卓资山熏鸡', isSelect: false }
    ],
    selectNum: 0
  },
  {
    index: 23,
    name: '西藏菜',
    city: [{ name: '西藏', value: '西藏菜', selected: false }],
    list: [
      { name: '青稞', isSelect: false },
      { name: '牦牛肉', isSelect: false },
      { name: '酥油茶', isSelect: false },
      { name: '糌粑', isSelect: false },
      { name: '青稞酒', isSelect: false },
      { name: '炸灌肺', isSelect: false },
      { name: '蒸牛舌', isSelect: false },
      { name: '氽灌肠', isSelect: false },
      { name: '火烧蕨麻猪', isSelect: false },
      { name: '夏河蹄筋', isSelect: false },
      { name: '爆焖羊羔肉', isSelect: false },
      { name: '吹肝', isSelect: false }
    ],
    selectNum: 0
  },
  {
    index: 24,
    name: '海南菜',
    city: [{ name: '海南', value: '海南菜', selected: false }],
    list: [
      { name: '文昌鸡', isSelect: false },
      { name: '加积鸭', isSelect: false },
      { name: '东山羊', isSelect: false },
      { name: '和乐蟹', isSelect: false },
      { name: '斋菜煲', isSelect: false },
      { name: '海南粉', isSelect: false },
      { name: '海南粽', isSelect: false },
      { name: '海南鸡饭', isSelect: false },
      { name: '东山烙饼', isSelect: false },
      { name: '黎族甜糟', isSelect: false },
      { name: '苗族五色饭', isSelect: false },
      { name: '椰丝糯米粑', isSelect: false },
      { name: '锦山煎堆', isSelect: false }
    ],
    selectNum: 0
  }
];
